export const
	space = ` `.charCodeAt(),
	semicolon = `;`.charCodeAt(),
	colon = `:`.charCodeAt(),
	equals = `=`.charCodeAt(),
	at = `@`.charCodeAt(),
	zero = `0`.charCodeAt(),
	nine = `9`.charCodeAt(),
	A = `A`.charCodeAt(),
	hashtag = `#`.charCodeAt(),
	bang = `!`.charCodeAt(),
	cr = `\r`.charCodeAt(),
	lf = `\n`.charCodeAt(),
	dash = `-`.charCodeAt(),
	backslash = `\\`.charCodeAt(),
	s = `s`.charCodeAt(),
	r = `r`.charCodeAt(),
	comma = `,`.charCodeAt(),
	forwardslash = `/`.charCodeAt(),
	t = `t`.charCodeAt()
